import { createClient } from "@supabase/supabase-js";

const supabase = createClient(
    "https://zrsnyumhwjsxnkugcukg.supabase.co",
    "sb_publishable_ZLSOwBM0FCEHLtU74eOJmQ_2yvayR0Y"
);

async function main() {
    console.log("=== 1. SIGN IN / UP TEST USER ===");
    const email = `workflow_test_${Date.now()}@codemedic.dev`;
    const password = "Password123!";
    const { data: authData, error: authError } = await supabase.auth.signUp({ email, password });
    if (authError || !authData.session) {
        console.error("Auth failed:", authError);
        process.exit(1);
    }
    const session = authData.session;
    const userId = session.user.id;
    console.log("Authenticated as user:", userId);

    console.log("\n=== 2. CALL generate-problem ===");
    const requirements = {
        topic: "Strings",
        difficulty: "Easy",
        pattern: "Two Pointers",
        dataStructure: "String",
        complexity: "O(n)"
    };

    const startTime = Date.now();
    const { data: problemData, error: problemError } = await supabase.functions.invoke(
        "generate-problem",
        {
            body: requirements,
            headers: {
                Authorization: `Bearer ${session.access_token}`
            }
        }
    );

    if (problemError || !problemData?.success) {
        console.error("generate-problem FAILED:", problemError || problemData);
        if (problemError?.context) {
            console.error("Context body:", await problemError.context.text());
        }
        process.exit(1);
    }

    const problem = problemData.problem;
    console.log(`Problem generated in ${Date.now() - startTime}ms:`);
    console.log("  ID:", problem.id);
    console.log("  Title:", problem.title);
    console.log("  Topic:", problem.topic);
    console.log("  Difficulty:", problem.difficulty);
    console.log("  Is Generated:", problem.is_generated);
    console.log("  Generated By:", problem.generated_by);
    console.log("  Hints count:", problem.hints?.length);
    console.log("  Examples count:", problem.examples?.length);
    console.log("  Starter Code length:", problem.starter_code?.length);
    console.log("  Execution Config:", problem.execution_config);

    if (problem.generated_by !== userId) {
        console.error(`MISMATCH: generated_by (${problem.generated_by}) !== authenticated userId (${userId})`);
        process.exit(1);
    }

    console.log("\n=== 3. CALL generate-test-cases ===");
    const testStartTime = Date.now();
    const { data: testData, error: testError } = await supabase.functions.invoke(
        "generate-test-cases",
        {
            body: {
                problemId: problem.id
            },
            headers: {
                Authorization: `Bearer ${session.access_token}`
            }
        }
    );

    if (testError || !testData?.success) {
        console.error("generate-test-cases FAILED:", testError || testData);
        if (testError?.context) {
            console.error("Context body:", await testError.context.text());
        }
        process.exit(1);
    }

    console.log(`Test cases generated in ${Date.now() - testStartTime}ms:`);
    console.log("  Problem ID:", testData.problemId);
    console.log("  Test Count:", testData.testCount);

    // Verify in database directly
    const { count: dbTestCount, error: countError } = await supabase
        .from("problem_test_cases")
        .select("*", { count: "exact", head: true })
        .eq("problem_id", problem.id);

    console.log(`Verified DB test cases count: ${dbTestCount} (Error: ${countError?.message || "none"})`);

    console.log("\n=== 4. CALL analyze-code ===");
    const analysisStartTime = Date.now();
    const studentThinking = {
        dataStructures: ["Array"],
        patterns: ["Two Pointers"],
        complexity: "O(n)"
    };

    const studentCode = `
class Solution {
public:
    bool solve(string s) {
        // Brute force nested loops instead of planned Two Pointers
        for (int i = 0; i < s.size(); i++) {
            for (int j = i + 1; j < s.size(); j++) {
                if (s[i] == s[j]) return false;
            }
        }
        return true;
    }
};
`;

    const { data: aiData, error: aiError } = await supabase.functions.invoke(
        "analyze-code",
        {
            body: {
                problem,
                thinking: studentThinking,
                code: studentCode,
                language: "C++",
                basicAnalysis: {
                    timeComplexity: "O(n²)",
                    spaceComplexity: "O(1)",
                    bruteForce: true
                },
                executionResult: {
                    status: "Accepted",
                    success: true,
                    passedTests: 5,
                    totalTests: 5
                }
            },
            headers: {
                Authorization: `Bearer ${session.access_token}`
            }
        }
    );

    if (aiError || !aiData?.success) {
        console.error("analyze-code FAILED:", aiError || aiData);
        if (aiError?.context) {
            console.error("Context body:", await aiError.context.text());
        }
        process.exit(1);
    }

    const diagnosis = aiData.diagnosis;
    console.log(`AI diagnosis received in ${Date.now() - analysisStartTime}ms:`);
    console.log("  Correctness:", diagnosis.correctness);
    console.log("  Approach:", diagnosis.approach);
    console.log("  Brute force detected:", diagnosis.brute_force);
    console.log("  Estimated Time Complexity:", diagnosis.time_complexity);
    console.log("  Thinking Observation:", diagnosis.thinking_observation);
    console.log("  Weakness:", diagnosis.weakness);
    console.log("  Hints count:", diagnosis.hints?.length);
    console.log("  Reference solution provided:", !!diagnosis.reference_solution);

    console.log("\n>>> ALL THREE EDGE FUNCTIONS VERIFIED END-TO-END WITH AUTH & GEMINI! <<<");
}

main().catch(err => {
    console.error("Unhandled verification error:", err);
    process.exit(1);
});
